export interface ArcadeGame {
  id: string;
  title: string;
  tagline: string;
  category: 'BOARD' | 'ARCADE' | 'CAR_RACING' | 'PUZZLE' | 'CARDS' | 'ACTION';
  iconEmoji: string;
  gradient: readonly [string, string];
  players: string; // '2 Players' | 'Split Screen' | 'Turn Based'
  rating: number; // 4.8 to 5.0
  playsCount: string;
  badge?: string;
  type: 'LUDO' | 'SNAKE_LADDER' | 'CAR_RACE' | 'TIC_TAC_TOE' | 'PONG' | 'MEMORY_MATCH' | 'REACTION_TAP' | 'ARCHERY' | 'BASKETBALL' | 'CONNECT4' | 'AIR_HOCKEY' | 'CHESS' | 'CHECKERS' | 'JENGA' | 'WORDLE' | 'CROSSWORD' | 'MINESWEEPER' | 'PIANO_TILES' | 'BUBBLE_POP' | 'BLACKJACK' | 'UNO_CARDS' | 'POKER' | 'MAHJONG' | 'BOWLING' | 'THUMB_WAR' | 'SPACE_RUNNER' | 'COOKING_RUSH' | 'DOODLE_GUESS' | 'SUDOKU' | 'TURBO_KART';
}

export const ARCADE_30_GAMES: ArcadeGame[] = [
  // --- CAR & RACING GAMES (2-Player) ---
  {
    id: 'car_racing_midnight',
    title: 'Midnight Couple Racer 🏎️',
    tagline: 'High-speed side-by-side car racing on neon highways',
    category: 'CAR_RACING',
    iconEmoji: '🏎️',
    gradient: ['#FF416C', '#FF4B2B'],
    players: '2 Players Live',
    rating: 4.9,
    playsCount: '24.5k',
    badge: 'POPULAR 🔥',
    type: 'CAR_RACE',
  },
  {
    id: 'turbo_kart_gp',
    title: 'Turbo Kart Couple GP 🏁',
    tagline: 'Go-kart racing with heart rockets, banana traps & turbo boosts',
    category: 'CAR_RACING',
    iconEmoji: '🏎️',
    gradient: ['#FA709A', '#FEE140'],
    players: 'Split Screen',
    rating: 4.8,
    playsCount: '19.2k',
    badge: 'HOT',
    type: 'TURBO_KART',
  },

  // --- CLASSIC BOARD & STRATEGY GAMES ---
  {
    id: 'ludo_supreme',
    title: 'Couple Ludo Supreme 🎲',
    tagline: 'Classic Ludo with romantic kiss & hug safezones',
    category: 'BOARD',
    iconEmoji: '🎲',
    gradient: ['#667EEA', '#764BA2'],
    players: 'Turn Based',
    rating: 5.0,
    playsCount: '48.1k',
    badge: 'FEATURED 🌟',
    type: 'LUDO',
  },
  {
    id: 'snake_and_ladder',
    title: 'Snakes & Ladders: Love Trail 🐍',
    tagline: 'Ladders give kisses & compliments, snakes give sweet forfeits',
    category: 'BOARD',
    iconEmoji: '🐍',
    gradient: ['#11998E', '#38EF7D'],
    players: 'Turn Based',
    rating: 4.9,
    playsCount: '32.4k',
    badge: 'NEW',
    type: 'SNAKE_LADDER',
  },
  {
    id: 'tic_tac_toe_xoxo',
    title: 'Tic-Tac-Toe: Kisses & Hugs (XOXO) ⭕❌',
    tagline: 'Get 3 in a row to win a real romantic reward!',
    category: 'BOARD',
    iconEmoji: '⭕',
    gradient: ['#FF6B8B', '#FF8E53'],
    players: 'Turn Based',
    rating: 4.9,
    playsCount: '55.3k',
    badge: 'TOP PLAYED',
    type: 'TIC_TAC_TOE',
  },
  {
    id: 'connect_four_hearts',
    title: 'Connect 4 Hearts 🔴🟡',
    tagline: 'Drop tokens and connect 4 glowing hearts to win',
    category: 'BOARD',
    iconEmoji: '🔴',
    gradient: ['#F857A6', '#FF5858'],
    players: 'Turn Based',
    rating: 4.8,
    playsCount: '21.0k',
    type: 'CONNECT4',
  },
  {
    id: 'couples_chess',
    title: 'Couples Chess Duel ♟️',
    tagline: 'Royal strategy with heart-themed pieces and speed timers',
    category: 'BOARD',
    iconEmoji: '♟️',
    gradient: ['#434343', '#000000'],
    players: 'Turn Based',
    rating: 4.7,
    playsCount: '15.6k',
    type: 'CHESS',
  },
  {
    id: 'couples_checkers',
    title: 'Speed Checkers ⚪⚫',
    tagline: 'Fast jump-and-capture board battle for lovers',
    category: 'BOARD',
    iconEmoji: '⚪',
    gradient: ['#8E2DE2', '#4A00E0'],
    players: 'Turn Based',
    rating: 4.6,
    playsCount: '12.8k',
    type: 'CHECKERS',
  },
  {
    id: 'block_tower_jenga',
    title: 'Love Jenga Block Tower 🧱',
    tagline: 'Pull wooden blocks without tumbling the romance tower',
    category: 'BOARD',
    iconEmoji: '🧱',
    gradient: ['#E65C00', '#F9D423'],
    players: 'Turn Based',
    rating: 4.8,
    playsCount: '18.4k',
    type: 'JENGA',
  },

  // --- ACTION & ARCADE SPLIT-SCREEN GAMES ---
  {
    id: 'glow_pong_clash',
    title: 'Glow Pong / Love Tennis 🏓',
    tagline: 'Split-screen paddle duel! First to 5 points wins a hug',
    category: 'ACTION',
    iconEmoji: '🏓',
    gradient: ['#00C9FF', '#92FE9D'],
    players: 'Split Screen',
    rating: 4.9,
    playsCount: '38.9k',
    badge: 'ADDICTIVE',
    type: 'PONG',
  },
  {
    id: 'air_hockey_neon',
    title: 'Glow Air Hockey Couple Clash 🏒',
    tagline: 'Fast-paced neon air hockey physics on a single phone',
    category: 'ACTION',
    iconEmoji: '🏒',
    gradient: ['#F12711', '#F5AF19'],
    players: 'Split Screen',
    rating: 4.9,
    playsCount: '27.3k',
    type: 'AIR_HOCKEY',
  },
  {
    id: 'reaction_time_tap',
    title: 'Reaction Tap Chemistry Duel ⚡',
    tagline: 'Wait for the screen to turn pink — fastest reflex tap wins!',
    category: 'ACTION',
    iconEmoji: '⚡',
    gradient: ['#FC466B', '#3F5EFB'],
    players: '2 Players Live',
    rating: 5.0,
    playsCount: '41.2k',
    badge: 'QUICK GAME',
    type: 'REACTION_TAP',
  },
  {
    id: 'cupid_archery',
    title: 'Cupid Archery Target Shoot 🏹',
    tagline: 'Aim your bow & shoot floating heart balloons for high scores',
    category: 'ACTION',
    iconEmoji: '🏹',
    gradient: ['#FF512F', '#DD2476'],
    players: '2 Players Live',
    rating: 4.8,
    playsCount: '29.7k',
    type: 'ARCHERY',
  },
  {
    id: 'basketball_shootout',
    title: 'Hoops Romance (Basketball) 🏀',
    tagline: 'Swipe to shoot 3-pointers into the couple basket',
    category: 'ACTION',
    iconEmoji: '🏀',
    gradient: ['#FF8008', '#FFC837'],
    players: '2 Players Live',
    rating: 4.7,
    playsCount: '22.1k',
    type: 'BASKETBALL',
  },
  {
    id: 'thumb_war_clash',
    title: 'Thumb War Championship 🥊',
    tagline: 'Hold down the ring and pin your partner’s thumb',
    category: 'ACTION',
    iconEmoji: '🥊',
    gradient: ['#EB3349', '#F45C43'],
    players: 'Split Screen',
    rating: 4.8,
    playsCount: '34.5k',
    type: 'THUMB_WAR',
  },
  {
    id: 'couple_bowling_3d',
    title: 'Couple 3D Bowling 🎳',
    tagline: 'Spin and roll bowling balls to score romantic strikes',
    category: 'ACTION',
    iconEmoji: '🎳',
    gradient: ['#4E54C8', '#8F94FB'],
    players: 'Turn Based',
    rating: 4.7,
    playsCount: '16.9k',
    type: 'BOWLING',
  },
  {
    id: 'space_love_runner',
    title: 'Space Love Runners 🚀',
    tagline: 'Co-op space obstacle dodging through asteroid belts',
    category: 'ACTION',
    iconEmoji: '🚀',
    gradient: ['#2E3192', '#1BFFFF'],
    players: 'Co-op Live',
    rating: 4.6,
    playsCount: '14.2k',
    type: 'SPACE_RUNNER',
  },

  // --- BRAIN, PUZZLE & MEMORY GAMES ---
  {
    id: 'memory_tile_flip',
    title: 'Couple Memory Match Pair 🧩',
    tagline: 'Flip cards and find matching couple stickers & polaroids',
    category: 'PUZZLE',
    iconEmoji: '🧩',
    gradient: ['#A8EDEA', '#FED6E3'],
    players: 'Turn Based',
    rating: 4.9,
    playsCount: '36.8k',
    badge: 'FUN & CUTE',
    type: 'MEMORY_MATCH',
  },
  {
    id: 'romantic_wordle',
    title: 'Secret Word Duel (Wordle) 🔤',
    tagline: 'Set a secret 5-letter word for your partner to guess in 6 tries',
    category: 'PUZZLE',
    iconEmoji: '🔤',
    gradient: ['#56AB2F', '#A8E063'],
    players: 'Turn Based',
    rating: 4.8,
    playsCount: '25.4k',
    type: 'WORDLE',
  },
  {
    id: 'love_crossword',
    title: 'Love Crossword Puzzle 🔍',
    tagline: 'Solve romantic crossword clues and love trivia together',
    category: 'PUZZLE',
    iconEmoji: '🔍',
    gradient: ['#3A7BD5', '#3A6073'],
    players: 'Co-op Live',
    rating: 4.7,
    playsCount: '18.1k',
    type: 'CROSSWORD',
  },
  {
    id: 'couple_minesweeper',
    title: 'Sweet Minefield (Love Finder) 💣',
    tagline: 'Uncover romantic gems without detonating surprise forfeits',
    category: 'PUZZLE',
    iconEmoji: '💎',
    gradient: ['#00B4DB', '#0083B0'],
    players: 'Turn Based',
    rating: 4.6,
    playsCount: '13.5k',
    type: 'MINESWEEPER',
  },
  {
    id: 'couple_sudoku_coop',
    title: 'Sudoku Co-op for Two 🔢',
    tagline: 'Solve tricky grid puzzles together as a power couple',
    category: 'PUZZLE',
    iconEmoji: '🔢',
    gradient: ['#614385', '#516395'],
    players: 'Co-op Live',
    rating: 4.5,
    playsCount: '11.2k',
    type: 'SUDOKU',
  },
  {
    id: 'doodle_guess_live',
    title: 'Couple Quick Doodle & Guess 🎨',
    tagline: 'Draw on the screen with your finger while your partner guesses',
    category: 'PUZZLE',
    iconEmoji: '🎨',
    gradient: ['#FF0844', '#FFB199'],
    players: '2 Players Live',
    rating: 4.9,
    playsCount: '31.0k',
    badge: 'POPULAR',
    type: 'DOODLE_GUESS',
  },

  // --- CARD, CASINO & CASUAL GAMES ---
  {
    id: 'couple_blackjack',
    title: 'Couple Blackjack 21 🃏',
    tagline: 'Hit or Stand! Bet love points against the romantic dealer',
    category: 'CARDS',
    iconEmoji: '🃏',
    gradient: ['#134E5E', '#71B280'],
    players: 'Turn Based',
    rating: 4.8,
    playsCount: '28.3k',
    type: 'BLACKJACK',
  },
  {
    id: 'uno_couple_clash',
    title: 'Uno: Couples Crazy Cards 🎴',
    tagline: 'Color matching with special romantic +2 Kisses & Skip cards',
    category: 'CARDS',
    iconEmoji: '🎴',
    gradient: ['#ED213A', '#93291E'],
    players: '2 Players Live',
    rating: 4.9,
    playsCount: '44.8k',
    badge: 'TOP FAVORITE',
    type: 'UNO_CARDS',
  },
  {
    id: 'poker_night_duo',
    title: 'Poker Night for Two ♠️',
    tagline: 'Texas Hold’em with romantic poker chip betting',
    category: 'CARDS',
    iconEmoji: '♠️',
    gradient: ['#0F2027', '#2C5364'],
    players: 'Turn Based',
    rating: 4.6,
    playsCount: '17.4k',
    type: 'POKER',
  },
  {
    id: 'mahjong_love_tiles',
    title: 'Mahjong Love Pairs 🀄',
    tagline: 'Match serene floral and couple symbols on the board',
    category: 'CARDS',
    iconEmoji: '🀄',
    gradient: ['#2C3E50', '#FD746C'],
    players: 'Turn Based',
    rating: 4.7,
    playsCount: '19.9k',
    type: 'MAHJONG',
  },

  // --- MUSIC, RHYTHM & CASUAL GAMES ---
  {
    id: 'piano_tiles_melody',
    title: 'Piano Tiles: Love Melody Tap 🎵',
    tagline: 'Tap falling keys in sync with beautiful romantic piano songs',
    category: 'ARCADE',
    iconEmoji: '🎵',
    gradient: ['#8A2387', '#E94057'],
    players: '2 Players Live',
    rating: 4.9,
    playsCount: '35.6k',
    badge: 'RHYTHM',
    type: 'PIANO_TILES',
  },
  {
    id: 'bubble_pop_romance',
    title: 'Bubble Pop Romance 🫧',
    tagline: 'Pop matching color love bubbles before the timer expires',
    category: 'ARCADE',
    iconEmoji: '🫧',
    gradient: ['#74EBD5', '#9FACE6'],
    players: '2 Players Live',
    rating: 4.7,
    playsCount: '23.8k',
    type: 'BUBBLE_POP',
  },
  {
    id: 'cooking_rush_couple',
    title: 'Couple Cooking Rush 🥑',
    tagline: 'Slice ingredients and assemble delicious burgers & pastas together',
    category: 'ARCADE',
    iconEmoji: '🥑',
    gradient: ['#F7971E', '#FFD200'],
    players: 'Co-op Live',
    rating: 4.9,
    playsCount: '39.0k',
    badge: 'SUPER FUN',
    type: 'COOKING_RUSH',
  },
];
